### PR TITLE
Remove "think like us."

### PR DESCRIPTION
**Pull request by williln**
I think we were going for "who work well with us," but I'd like to make it clear that we value diverse perspectives. What do y'all think?

### CODE REVIEW

**Comment by aniav** [comment]
+1

**Comment by olasitarska** [comment]
Yes, that was definitely meant to be heard as "people who work like us", and wording is my mistake. But do you think that instead of removing this completely, we could keep the original intention, and word it better so it doesn't sound like I was dead tired writing it at Django Girls booth at EuroPython? :) 

I think it's an important criteria when we think "if that person would be a good addition to a team", and I wouldn't like to remove it completely.

**Comment by bmispelon** [comment]
What about "people who share our values and offer new perspectives"?

**Comment by olasitarska** [comment]
@bmispelon :+1:

**Comment by williln** [comment]
:+1:

**Comment by asendecka** [comment]
+1

2015-08-07 21:32 GMT+01:00 Lacey Williams Henschel <notifications@github.com

**Comment by phalt** [comment]
:+1:

**Pull request merged**
