### PR TITLE
Add web apps to update virtualenv for

### PR DESCRIPTION
**Pull request by amakarudze**
Recently realised that we are using 3 web apps for which we need to update Python version and virtualenv after upgrade. I have updated documentation to reflect that for future reference.

### CODE REVIEW

**Comment by carltongibson** [comment]
Hey @amakarudze thanks for this.

Do we know what each of these are for?

**Comment by amakarudze** [comment]
@carltongibson you're welcome. No we don't know yet but we reload them all when we do automatic deployment and I noticed when I was getting server errors one of the logs was for one of these. We will need to investigate what they all do. 

For now, I am just documenting how things are so that if we ever change them we just update.

**Comment by carltongibson** [comment]
Ok... 🙂

We can work it out, and remove what we don't need. And maybe unify what we do. 

Slowly slowly. 👍

**Comment by amakarudze** [comment]
Yeah that would great!

**Comment by amakarudze** [comment]
@carltongibson all 3 web apps have same settings for virtualenv, source code, working directory, static files root and uploads root. Only one has a CNAME configured, so am guessing they are sharing the load somehow because they are serving the same site. That's what I can speculate on for now.

**Comment by amakarudze** [comment]
> Hey @amakarudze thanks for this.
> 
> Do we know what each of these are for?

@carltongibson I have checked and all the apps serve the Django Girls website, using same code base and same virtualenv. However, each contains own environment variables in own `wsgi` file.

**Pull request merged**
